### ISSUE TITLE
Graph scales down

### ISSUE THREAD

**Issue by FlarosOverfield** [Nrosa01/pmd-quiz-online#1]
![Vega - Personality Quiz](https://user-images.githubusercontent.com/24918282/199985058-6a329151-0e7e-4d81-92b6-adcd25028409.png)

The natures graph seems to automatically scale down to the highest value so it looks like you chose all the Sassy answers perfectly, even when you didn't

I chose the non-sassy answers at the "big bed", "difficult task", "karaoke", and "blaming someone else" questions. It would be neat to have the graph scale so it shows how far away you are from the max value

It would also be neat to have the quiz ask for gender at the start, and change the window border to red or blue depending what you answer, or stay green for nonbinary

**Comment by Nrosa01** [comment]
Hi! I'm aware of this and I did that on purpose. points are between 0-1 and in the normal mode you usually get like 0.05-0.15 points in hte max nature, if I don't scale the graph it looks bad. I'm aware this can lead to confussion, I'll try to find a better way to display the data.

I removed the gender question on purpose, what if someone doesn't identify as one of those two genders? It's easier for me to just use a neutral color and to give you both pokemons.
