### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by luca-bertero** [Nrosa01/pmd-quiz-online#3]
Hi! Really great project that take me back at the time were I was spending hours on this game.
I want you to know that i am translating the project in italian. 
It will take a bit because I only have my free time to work on it but I will look to make a PR asap :)

**Comment by Nrosa01** [comment]
Hi! Thank you a lot! 

But please don't manually translate the 63 questions. Another person already contacted me to translate the project to italian, and it seems there is some italian wiki that has the data. I'm waiting for this person to send me the link so I can write a script that converts the HTML to my JSON format (that's way faster than writing each question manually). But meanwhile I would appreciate if you helped me translating the other files ^^

This is the screenshot I got:
![screenshot](https://media.discordapp.net/attachments/808381067303190554/1039255919516725248/unknown.png?width=315&height=682)

I assume you did it but just in case, don't forget to check [the contributing file](https://github.com/Nrosa01/pmd-quiz-online/blob/main/Contributing.md)

**Comment by luca-bertero** [comment]
Great! The hard part is translating the nature description. I didn't find it in the internet, so I'm helping me with the original game

**Comment by Nrosa01** [comment]
Ooof, that's a lot of work, take it with calm. You may also ask in skytemple discord server, some people know you to rip data, the italian original translation could be extracted from some EU ROM. At first I was going to do it myself but I don't have enough time now to learn to use a new tool 😔

**Comment by luca-bertero** [comment]
Huuuuge!! I didn't know about this tool. I found all the italian string. There are also the other language in order!!

**Comment by Nrosa01** [comment]
Uhhh that sounds cool! I thought it would be harder/more time consuming. So then it should be easy to add the italian language (and even french and german).  Are you doing a PR or do you want me to write a script that turns the data into my JSON formats? I don't know how it's formatted there but as long as it follows some pattern I can do it

**Comment by luca-bertero** [comment]
It's a csv file, but don't worry, when it will be all done I will do a PR

**Comment by Nrosa01** [comment]
Alright, if you need any help tell me. Thank you! ^^

**Comment by Nrosa01** [comment]
Italian translation pull request has been merged. Thank you! ^^
